Fixed clickables objects
daibogh/boldinnov pull request #2
Opened 2019-03-30 17:42 UTC by xLoSyAsHx

Added slicing for clickables array (to fit into data from DB)
Added all points to map svg

2019-04-02 13:29 UTC, daibogh requested changes
change one line in your code, and add new instances in database

2019-04-02 13:29 UTC, daibogh commented on assets/src/js/models/LoadedMap.tsx
> +            ellipses = ellipses.slice(0, data.length - 1)
just data.length

2019-04-02 20:59 UTC, xLoSyAsHx commented on assets/src/js/models/LoadedMap.tsx
> +            ellipses = ellipses.slice(0, data.length - 1)
Done

2019-04-03 10:35 UTC, daibogh approved these changes

2019-04-03 10:36 UTC, merged